apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  source:
    path: apps/metallb
    repoURL: https://github.com/rfdez/raspberrypi-kubernetes
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  project: default
  ignoreDifferences:
    - kind: Serviceaccount
      jsonPointers:
      - /imagePullSecrets
